name: Test
on:
  push:
    paths-ignore:
      - .github/**
      - README.md
      - .gitignore

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.7", "3.8", "3.9", "3.10"]
        pytorch-version: ["1.12.0"]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          pip install torch=${{ matrix.pytorch-version }} pytest
          pip install torch-scatter -f https://data.pyg.org/whl/torch-${{ matrix.pytorch-version }}+cpu.html
          pip install torch-sparse -f https://data.pyg.org/whl/torch-${{ matrix.pytorch-version }}+cpu.html
          pip install torch-geometric

      - name: Run tests
        run: python -m pytest tests -v
